name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Output Run ID
        run: echo ${{ github.run_id }}

      - name: Output Run Number
        run: echo ${{ github.run_number }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Building the installer
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "Minima.iss"
        shell: cmd

      - name: Upload the installer as an artifact
        uses: actions/upload-artifact@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          path: "Output/minima-0.98.44-setup.exe"
          name: minima-setup